brew "fnm"

cask "brave-browser"
cask "claude-code"
cask "cold-turkey-blocker"
cask "ghostty"
cask "jetbrains-toolbox"
cask "obsidian"
cask "raycast"
cask "rekordbox"
cask "steam"
cask "visual-studio-code"
